resources:
  jobs:
    products_etl_job:
      name: products_etl_job
      trigger:
        periodic:
          interval: 1
          unit: DAYS
      tasks:
        - task_key: pipeline-task-0985ce9e-579b-44ad-b3e5-b13e31bd7582
          pipeline_task:
            pipeline_id: ${resources.pipelines.products_etl.id}
      notification_settings:
        no_alert_for_skipped_runs: true
      email_notifications:
        no_alert_for_skipped_runs: true
        on_failure:
          - nishanty@gmail.com
      queue:
        enabled: true
